---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app
  namespace: argocd2
  annotations:
    argocd-image-updater.argoproj.io/image-list: "hello-world=imshashannk/hello-world:latest"
    argocd-image-updater.argoproj.io/update-strategy: "latest"
spec:
  project: default
  source:
    repoURL: https://github.com/imshashannk/Python_argocd.git
    path: manifests
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: argocd2
  annotations:
    argocd-image-updater.argoproj.io/hello-world.image-name: "imshashannk/hello-world"
    argocd-image-updater.argoproj.io/hello-world.pull-policy: "Always"
    argocd-image-updater.argoproj.io/hello-world.tag: "latest"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: imshashannk/hello-world:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
