apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  annotations:
    argocd-image-updater.argoproj.io/update-strategy: "latest"  # This tells ArgoCD Image Updater to track the latest tag
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: imshashannk/hello-world:latest
        ports:
        - containerPort: 80

