apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app
  namespace: argocd2
  annotations:
    # Annotation to specify which image to update
    argocd-image-updater.argoproj.io/image-list: "hello-world=imshashannk/hello-world:latest"
    # Annotation to define the update strategy
    argocd-image-updater.argoproj.io/update-strategy: "latest"
spec:
  project: default
  source:
    repoURL: https://github.com/imshashannk/Python_argocd.git
    path: manifests
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
