apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/hello-world.image-name: "imshashannk/hello-world"
    argocd-image-updater.argoproj.io/hello-world.update-strategy: "name"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: imshashannk/hello-world # No tag here for dynamic updates
        imagePullPolicy: Always
        ports:
        - containerPort: 8080  
