apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  annotations:
    argocd-image-updater.argoproj.io/update-strategy: "latest"
    argocd-image-updater.argoproj.io/hello-world.image-name: "imshashannk/hello-world"
    argocd-image-updater.argoproj.io/hello-world.pull-policy: "IfNotPresent"
    argocd-image-updater.argoproj.io/hello-world.tag: "latest"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: imshashannk/hello-world:latest
        ports:
        - containerPort: 80
