apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: imshashannk/hello-world:myalias
    argocd-image-updater.argoproj.io/myalias.update-strategy: tag
    argocd-image-updater.argoproj.io/myalias.tag: latest
    argocd-image-updater.argoproj.io/myalias.write-back-method: git
    argocd-image-updater.argoproj.io/myalias.git-branch: main
    argocd-image-updater.argoproj.io/myalias.force-update: "true"

spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: imshashannk/hello-world
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
