apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: argocd  # Make sure this matches the namespace where your application will run
  annotations:
    argocd-image-updater.argoproj.io/image-list: imshashannk/hello-world
    argocd-image-updater.argoproj.io/imshashannk-hello-world.update-strategy: latest
    argocd-image-updater.argoproj.io/imshashannk-hello-world.write-back-method: git
    argocd-image-updater.argoproj.io/imshashannk-hello-world.git-branch: main
    argocd-image-updater.argoproj.io/imshashannk-hello-world.force-update: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: imshashannk/hello-world:1.0.89
        imagePullPolicy: Always
        ports:
        - containerPort: 80  # The port your container listens on
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: argocd  # Ensure this matches the namespace
spec:
  selector:
    app: hello-world  # Ensure this matches the label in the deployment
  ports:
    - protocol: TCP
      port: 80          # Expose port 80 for external access
      targetPort: 80    # The container port the service will forward to
      nodePort: 30080   # Custom NodePort for accessing the service externally
  type: NodePort       # Exposes the service via a NodePort
