name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the action when you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ imshashannk}}
        password: ${{ Docker@321 }}

    - name: Build Docker image
      run: |
        docker build -t imshashannk/hello-world:latest .

    - name: Push Docker image
      run: |
        docker push imshashannk/hello-world:latest
