name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Updated to latest version
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Updated to latest version
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3  # Updated to latest version
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get Latest Tag and Increment
      id: tag
      run: |
        IMAGE_NAME="imshashannk/hello-world"
        
        # Fetch latest tag and increment
        LATEST_TAG=$(curl -s "https://registry.hub.docker.com/v1/repositories/$IMAGE_NAME/tags" | jq -r '.[].name' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
        
        if [ -z "$LATEST_TAG" ]; then
          NEW_TAG="1.0.0"  # Initialize if no previous tag found
        else
          MAJOR=$(echo "$LATEST_TAG" | cut -d. -f1)
          MINOR=$(echo "$LATEST_TAG" | cut -d. -f2)
          PATCH=$(echo "$LATEST_TAG" | cut -d. -f3)
          PATCH=$((PATCH + 1))
          NEW_TAG="$MAJOR.$MINOR.$PATCH"
        fi
        
        echo "New tag is $NEW_TAG"
        echo "tag=$NEW_TAG" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4  # Updated to latest version
      with:
        context: .
        push: true
        tags: |
          imshashannk/hello-world:${{ env.tag }}  # Incremented tag
          imshashannk/hello-world:latest          # Optional "latest" tag
