name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build, tag, and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: |
            imshashannk/hello-world:latest
          push: true

      # Configure Git for committing the updated tag to the repository
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      # Update Deployment YAML with the new tag and commit the change
      - name: Update Deployment YAML
        run: |
          # Ensure the latest tag is in the deployment YAML
          sed -i 's|image: imshashannk/hello-world:.*|image: imshashannk/hello-world:latest|' manifests/deployment.yaml

          # Commit the changes if there’s an update
          git add manifests/deployment.yaml
          git commit -m "Update Docker image to latest version"
          git push origin main
