name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Get Latest Tag and Increment
      id: version
      run: |
        # Fetch all tags to get the latest one
        git fetch --tags

        # Get the latest tag (if any)
        LATEST_TAG=$(git describe --tags --abbrev=0 || echo "v0")

        # Extract version number (e.g., "v1", "v2", etc.)
        VERSION_NUMBER=$(echo $LATEST_TAG | sed 's/v//')

        # Increment version number
        NEW_VERSION=$((VERSION_NUMBER + 1))
        NEW_TAG="v$NEW_VERSION"

        # Output the new tag for later use
        echo "New tag: $NEW_TAG"
        echo "tag=$NEW_TAG" >> $GITHUB_ENV

    - name: Create Git Tag and Push
      run: |
        # Create and push the new tag if it doesn't already exist
        git tag ${{ env.tag }}
        git push origin ${{ env.tag }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          imshashannk/hello-world:${{ env.tag }}
          imshashannk/hello-world:latest
