name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get Latest Version Tag
      id: version
      run: |
        VERSION_FILE=".version"
        
        # Check if version file exists, else initialize with 0
        if [[ -f "$VERSION_FILE" ]]; then
          VERSION=$(cat $VERSION_FILE)
        else
          VERSION=0
        fi
        
        # Increment version
        NEW_VERSION=$((VERSION + 1))
        echo "$NEW_VERSION" > $VERSION_FILE
        echo "New version is $NEW_VERSION"
        echo "tag=$NEW_VERSION" >> $GITHUB_ENV

    - name: Commit Version File
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add .version
        git commit -m "Increment version to ${{ env.tag }}"
        git push

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          imshashannk/hello-world:${{ env.tag }}
          imshashannk/hello-world:latest
