name: Docker Image Update, Scan, and Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for advanced build options
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Get Latest Version Tag and Increment for Docker Image
      - name: Get Latest Version Tag and Increment
        id: version
        run: |
          IMAGE_NAME="imshashannk/hello-world"
          TAGS=$(curl -s "https://hub.docker.com/v2/repositories/$IMAGE_NAME/tags/" | jq -r '.results[].name')
          LATEST_TAG=$(echo "$TAGS" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          if [ -z "$LATEST_TAG" ]; then
            NEW_TAG="1.0.0"
          else
            IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_TAG"
            PATCH=$((PATCH + 1))
            NEW_TAG="$MAJOR.$MINOR.$PATCH"
          fi
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      # Step 5: Build Docker Image with the New Tag
      - name: Build Docker Image
        run: |
          docker build -t imshashannk/hello-world:${{ env.NEW_TAG }} .

      # Step 6: Cache Trivy DB for faster vulnerability scans
      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            trivy-db-${{ runner.os }}-

      # Step 7: Set up Trivy for Vulnerability Scanning
      - name: Set up Trivy
        uses: aquasecurity/setup-trivy@v0.2.2
        with:
          version: 'latest'

      # Step 8: Run Trivy Vulnerability Scan on the Docker Image
      - name: Run Trivy Vulnerability Scan
        run: |
          trivy image --ignore-unfixed --severity HIGH,CRITICAL imshashannk/hello-world:${{ env.NEW_TAG }} --cache-dir ~/.cache/trivy || exit 1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # Step 9: Push Docker Image to Docker Hub if the scan is successful
      - name: Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: imshashannk/hello-world:${{ env.NEW_TAG }}

      # Step 10: Update Deployment YAML with the new Docker Image Tag
      - name: Update Deployment YAML
        run: |
          sed -i 's|image: imshashannk/hello-world:.*|image: imshashannk/hello-world:${{ env.NEW_TAG }}|' manifests/deployment.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add manifests/deployment.yaml
          git commit -m "Update Docker image to version ${{ env.NEW_TAG }}"
          git push origin main

      # Step 11: Set up Python environment for SonarCloud analysis
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 12: Install Python Dependencies for SonarCloud if any
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

      # Step 13: Run SonarCloud Code Analysis
      - name: Run SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@v1.3
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
