name: Docker Image Update, Scan, and Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx for building multi-platform images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Get the latest version tag and increment it
      - name: Get Latest Version Tag and Increment
        id: version
        run: |
          IMAGE_NAME="imshashannk/hello-world"
          TAGS=$(curl -s "https://hub.docker.com/v2/repositories/$IMAGE_NAME/tags/" | jq -r '.results[].name')
          LATEST_TAG=$(echo "$TAGS" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          if [ -z "$LATEST_TAG" ]; then
            NEW_TAG="1.0.0"
          else
            IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_TAG"
            PATCH=$((PATCH + 1))
            NEW_TAG="$MAJOR.$MINOR.$PATCH"
          fi
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t imshashannk/hello-world:${{ env.NEW_TAG }} .

      # Cache Trivy DB
      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            trivy-db-${{ runner.os }}-

      # Set up Trivy for scanning vulnerabilities
      - name: Set up Trivy
        uses: aquasecurity/setup-trivy@v0.2.2
        with:
          version: 'latest'

      # Run Trivy Vulnerability Scan
      - name: Run Trivy Vulnerability Scan
        run: |
          if [ -d "~/.cache/trivy/db" ]; then
            trivy image --ignore-unfixed --severity HIGH,CRITICAL imshashannk/hello-world:${{ env.NEW_TAG }} --cache-dir ~/.cache/trivy --skip-db-update
          else
            trivy image --ignore-unfixed --severity HIGH,CRITICAL imshashannk/hello-world:${{ env.NEW_TAG }} --cache-dir ~/.cache/trivy
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # Push Docker Image to Docker Hub
      - name: Push Docker Image
        if: success()
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: imshashannk/hello-world:${{ env.NEW_TAG }}

      # Update Deployment YAML file with the new image tag
      - name: Update Deployment YAML
        run: |
          sed -i 's|image: imshashannk/hello-world:.*|image: imshashannk/hello-world:${{ env.NEW_TAG }}|' manifests/deployment.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if git diff --quiet manifests/deployment.yaml; then
            echo "No changes to commit"
          else
            git add manifests/deployment.yaml
            git commit -m "Update Docker image to latest version: ${{ env.NEW_TAG }}"
            git push origin main
          fi

      # Install SonarScanner (ensure it's the version compiled for Java 17)
      - name: Install SonarScanner 4.6 (compatible with Java 17)
        run: |
          curl -sSLo sonar-scanner-cli-4.6.2.2472-linux.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip
          export SONAR_SCANNER_HOME=$(pwd)/sonar-scanner-4.6.2.2472-linux
          export PATH=$SONAR_SCANNER_HOME/bin:$PATH
          echo "SonarScanner is installed and available at $SONAR_SCANNER_HOME"
          echo "$SONAR_SCANNER_HOME/bin" >> $GITHUB_PATH  # Add SonarScanner bin folder to PATH permanently

      # Set JAVA_HOME to Java 17
      - name: Set JAVA_HOME to Java 17
        run: |
          echo "JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_PATH

      # Run SonarCloud Analysis using SonarScanner
      - name: Run SonarCloud Analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=$GITHUB_REPOSITORY \
            -Dsonar.organization=your-organization \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
