name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Load current version
      id: vars
      run: |
        if [ ! -f VERSION ]; then echo "1.0.0" > VERSION; fi
        version=$(cat VERSION)
        echo "Current version is $version"
        echo "version=$version" >> $GITHUB_ENV

    - name: Increment version
      run: |
        version=$(cat VERSION)
        IFS='.' read -r major minor patch <<<"$version"
        new_version="$major.$minor.$((patch+1))"
        echo "New version is $new_version"
        echo $new_version > VERSION
        echo "version=$new_version" >> $GITHUB_ENV
      shell: bash

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          imshashannk/hello-world:${{ env.version }}  # Tag with new version
          imshashannk/hello-world:latest              # Optionally tag as "latest"

    - name: Commit new version
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add VERSION
        git commit -m "Bump version to ${{ env.version }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
