name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get Latest Version from GitHub Releases
      id: version
      run: |
        # Fetch the latest release tag
        LATEST_VERSION=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases | jq -r '.[0].tag_name' | grep -E '^[0-9]+$' || echo "0")
        
        # Increment version
        NEW_VERSION=$((LATEST_VERSION + 1))
        echo "New version is $NEW_VERSION"
        echo "tag=$NEW_VERSION" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          imshashannk/hello-world:${{ env.tag }}
          imshashannk/hello-world:latest

    - name: Create GitHub Release for Version Tracking
      uses: actions/create-release@v1
      with:
        tag_name: "${{ env.tag }}"
        release_name: "Version ${{ env.tag }}"
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
