name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get Latest Git Tag and Increment
      id: version
      run: |
        # Fetch the latest git tag (or use v0 if no tags exist)
        LATEST_TAG=$(git describe --tags --abbrev=0 || echo "v0")
        
        # Extract the version number (e.g., "v1", "v2", etc.)
        VERSION_NUMBER=$(echo $LATEST_TAG | sed 's/v//')
        
        # Increment the version number
        NEW_VERSION=$((VERSION_NUMBER + 1))
        NEW_TAG="v$NEW_VERSION"
        
        # Set the tag as an environment variable
        echo "New tag is $NEW_TAG"
        echo "tag=$NEW_TAG" >> $GITHUB_ENV

    - name: Create New Git Tag and Push
      run: |
        # Create a new Git tag with the incremented version
        git tag ${{ env.tag }}
        git push origin ${{ env.tag }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          imshashannk/hello-world:${{ env.tag }}
          imshashannk/hello-world:latest
