name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get Latest Version Tag and Increment
      id: version
      run: |
        IMAGE_NAME="imshashannk/hello-world"
        
        # Fetch the latest numeric tag and increment
        LATEST_TAG=$(curl -s "https://registry.hub.docker.com/v1/repositories/$IMAGE_NAME/tags" | jq -r '.[].name' | grep -E '^[0-9]+$' | sort -n | tail -n 1)
        
        if [ -z "$LATEST_TAG" ]; then
          NEW_TAG="1"  # Start with 1 if no previous tag exists
        else
          NEW_TAG=$((LATEST_TAG + 1))
        fi
        
        echo "New tag is $NEW_TAG"
        echo "tag=$NEW_TAG" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          imshashannk/hello-world:${{ env.tag }}
          imshashannk/hello-world:latest
