name: Slack Notifications

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Trivy Vulnerability Scan"]
    types:
      - completed

jobs:
  notify_on_commit_success:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification for successful commit
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"🚀 Commit to main branch was successful! Commit: '${{ github.sha }}'. Repository: '${{ github.repository }}'"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

  notify_on_job_failure:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    needs: [trivy_scan]  # Runs if the trivy scan fails
    steps:
      - name: Send Slack notification for job failure
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ The GitHub Action job has failed. Please check the details in the Actions tab for more information."}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
